name: Git Workshop Demo

on: 
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'chore/**'
      - main
  
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello GitHub Actions"

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: build Production
        run: echo "build job2"